force-app/main/default/objects/A01_DaylySales__c/A01_DaylySales__c.object-meta.xml
<CustomObject>
    <label>A01_日次売上</label>
    <nameField>
        <label>A01_日次売上名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_DaylySales__c/fields/CalculationStatus__c.field-meta.xml
<CustomField>
    <fullName>CalculationStatus__c</fullName>
    <label>集計フラグ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>未集計</fullName>
                <default>true</default>
                <label>未集計</label>
            </value>
            <value>
                <fullName>集計済</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/CostSalary__c.field-meta.xml
<CustomField>
    <fullName>CostSalary__c</fullName>
    <label>費用(給料)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>年月日</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <label>売上</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/StoreR__c.field-meta.xml
<CustomField>
    <fullName>StoreR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>販売店情報</label>
    <referenceTo>A01_Store__c</referenceTo>
    <relationshipLabel>A01_日次売上</relationshipLabel>
    <relationshipName>A01</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/A01_MonthlySales__c.object-meta.xml
<CustomObject>
    <label>A01_月次売上</label>
    <nameField>
        <label>A01_月次売上名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_MonthlySales__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>承認ステータス</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>未申請</fullName>
                <default>true</default>
                <label>未申請</label>
            </value>
            <value>
                <fullName>申請中</fullName>
            </value>
            <value>
                <fullName>承認済</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/Monthly__c.field-meta.xml
<CustomField>
    <fullName>Monthly__c</fullName>
    <label>年月</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/MonthlySales__c.field-meta.xml
<CustomField>
    <fullName>MonthlySales__c</fullName>
    <label>月次売上</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/StoreR__c.field-meta.xml
<CustomField>
    <fullName>StoreR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>販売店情報</label>
    <referenceTo>A01_Store__c</referenceTo>
    <relationshipLabel>A01_月次売上</relationshipLabel>
    <relationshipName>A011</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/A01_Store__c/A01_Store__c.object-meta.xml
<CustomObject>
    <label>A01_販売店情報</label>
    <nameField>
        <label>A01_販売店情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/A01_DaylySales_TotalingHandler.cls
public class A01_DaylySales_TotalingHandler {

    public static void checkItemValue(A01_DaylySales__c[] arr, boolean isInsertFlg) {
        date ymd = arr[0].Day__c;

        for (A01_DaylySales__c obj : arr) {
            //月次の売上の必須入力チェック
            if (obj.Sales__c == null) {
                obj.Sales__c.addError('日次売上・売上に金額をご記入ください。');
            }
        }

        if (isInsertFlg) {
            //新規登録の場合、同じの年月日が存在すれば、エラーとなります。
            list<A01_DaylySales__c> retList = [select Id,Name,StoreR__r.Id from A01_DaylySales__c where StoreR__c =:arr[0].StoreR__c and Day__c =: ymd];
 
            if (retList.size() > 0) {
                //年月日の存在チェック
                arr[0].Day__c.addError('年月日はすでに登録されましたので、年月日をご変更ください。');
            }
        }

        for (A01_DaylySales__c rec : arr) {
            //TriggerのBeforeにはTrigger.New or Trigger.Oldを直接に更新できません。
            rec.CalculationStatus__c = '集計済';
            rec.CostSalary__c = 2000;
        }
    }

    //-------------------更新
    /**
     * 日次売上が新規登録される場合
     */
    public static void calculationPriceForInsert(A01_DaylySales__c[] arrNew){

        //月次集計年月日の算出
        Date inputDt = getMonthlyFirstDay(arrNew[0]);

        list<A01_MonthlySales__c> monthlyList = [select Id,MonthlySales__c,StoreR__r.Id,Monthly__c from A01_MonthlySales__c where StoreR__c = :arrNew[0].StoreR__c and Monthly__c = :inputDt];

        A01_MonthlySales__c obj = null;
        if (monthlyList.size() == 0) {
            //新規登録
            insert setMonthlyDataInfoForInsert(arrNew,inputDt);
        } else {
            //更新
            update setMonthlyDataInfoForUpdate(monthlyList,arrNew,null);
        }
        
 
    }

    /**
     * 日次売上が更新される場合
     */
    public static void calculationPriceForUpdate(A01_DaylySales__c[] arrNew,A01_DaylySales__c[] arrOld) {
        //月次集計年月日の算出
        Date inputDt = getMonthlyFirstDay(arrNew[0]);

        list<A01_MonthlySales__c> monthlyList = [select Id,MonthlySales__c,StoreR__r.Id,Monthly__c from A01_MonthlySales__c where StoreR__c = :arrNew[0].StoreR__c and Monthly__c = :inputDt];
        A01_MonthlySales__c obj = null;
        if (monthlyList.size() == 0) {
            //新規登録
            insert setMonthlyDataInfoForInsert(arrNew,inputDt);
        } else {
            A01_MonthlySales__c resultForUpdate = setMonthlyDataInfoForUpdate(monthlyList,arrNew,arrOld);
            //更新
            update resultForUpdate;
        }
 
    }
    
    private static Date getMonthlyFirstDay(A01_DaylySales__c newDaylyInfo) {
        Date dt = newDaylyInfo.Day__c;
        Integer saleYear = dt.year();
        Integer saleMonth = dt.month();
        Integer saleDay = 1;
        return Date.newInstance(saleYear, saleMonth, saleDay);
    }

    private static A01_MonthlySales__c setMonthlyDataInfoForInsert(A01_DaylySales__c[] arrNew,Date inputDt) {
        A01_MonthlySales__c retObj = new A01_MonthlySales__c();
        retObj.Name = string.valueof(arrNew[0].StoreR__c) + string.valueof(inputDt);
        retObj.StoreR__c = arrNew[0].StoreR__c;//販売店情報
        retObj.Monthly__c = inputDt;//月次集計年月日
        retObj.ApprovalStatus__c = '未申請';//承認ステータス
        retObj.MonthlySales__c = arrNew[0].Sales__c;//月次売上
        return retObj;
    }

    private static A01_MonthlySales__c setMonthlyDataInfoForUpdate(list<A01_MonthlySales__c> monthlyDataList,A01_DaylySales__c[] arrNew,A01_DaylySales__c[] arrOld) {

        A01_MonthlySales__c retObj = monthlyDataList.get(0);
        //売上の合計を設定する
        if (arrOld == null) {
            retObj.MonthlySales__c += arrNew[0].Sales__c;//月次売上
        } else {
            retObj.MonthlySales__c += arrNew[0].Sales__c - arrOld[0].Sales__c;//月次売上
        }

        return retObj;
    }


}