force-app/main/default/objects/A01_DaylySales__c/A01_DaylySales__c.object-meta.xml
<CustomObject>
    <label>A01_日次売上</label>
    <nameField>
        <label>A01_日次売上名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_DaylySales__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>原価</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/CostHydroelectric__c.field-meta.xml
<CustomField>
    <fullName>CostHydroelectric__c</fullName>
    <label>費用(水電)</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/CostRental__c.field-meta.xml
<CustomField>
    <fullName>CostRental__c</fullName>
    <label>費用(賃貸)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/CostSalary__c.field-meta.xml
<CustomField>
    <fullName>CostSalary__c</fullName>
    <label>費用(給料)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>年月日</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <label>利益</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <label>売上</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/StoreNoDay__c.field-meta.xml
<CustomField>
    <fullName>StoreNoDay__c</fullName>
    <formula>StoreR__r.StoreNo__c &amp;  TEXT(Day__c)</formula>
    <label>店番年月日</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/StoreR__c.field-meta.xml
<CustomField>
    <fullName>StoreR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>販売店情報</label>
    <referenceTo>A01_Store__c</referenceTo>
    <relationshipLabel>A01_日次売上</relationshipLabel>
    <relationshipName>A01</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/A01_Store__c/A01_Store__c.object-meta.xml
<CustomObject>
    <label>A01_販売店情報</label>
    <nameField>
        <label>A01_販売店情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_Store__c/fields/StoreName__c.field-meta.xml
<CustomField>
    <fullName>StoreName__c</fullName>
    <label>店名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/A01_StoreMonthlySalesDetailControl.cls
public class A01_StoreMonthlySalesDetailControl {
	//【申請】ボタン
	public boolean btnApplyFlg {get;set;}
	//【承認・否認】ボタン
	public boolean btnApproveFlg {get;set;}
	public string selStoreName { get; set; }
	public string selMonthly { get; set; }

	//画面明細リストオブジェクト
	public list<A01_DaylySales__c> searchResultList { get; set; }
	public A01_StoreMonthlySalesDetailControl() {
		selStoreName =(string) ApexPages.currentPage().getParameters().get('inputStoreName');
		selMonthly =(string) ApexPages.currentPage().getParameters().get('inputMonthly');

		string sql = 'select Id, StoreR__r.StoreName__c,' +
		'Day__c,' +
		'Sales__c,' +
		'Cost__c,' +
		'Profit__c,' +
		'CostHydroelectric__c,' +
		'CostSalary__c,' +
		'CostRental__c ' +
		'from A01_DaylySales__c ' +
		'where StoreR__r.StoreName__c = \'' + selStoreName + '\'' +
		' and Day__c like \'' + selMonthly + '%\'';
		system.debug('XXXXX' + sql);
		searchResultList = Database.query(sql);

		if(searchResultList.size() == 0) {
			//申請ボタンの非活性
			btnApplyFlg = false;
			//承認・否認ボタンの非活性
			btnApproveFlg = false;
			loadCsvFlg= 'true';
		} else {
			//申請ボタンの非活性
			btnApplyFlg = false;
			//承認・否認ボタンの非活性
			btnApproveFlg = true;
			loadCsvFlg= 'false';
		}

		getLoadFiles();
	}

	/*申請 */
	public Pagereference doRequest() {
		update searchResultList;
		return null;
	}

	/*承認 */
	public Pagereference doApproval() {
		return null;
	}

	/*否認 */
	public Pagereference doDenial() {
		return null;
	}

	public string fileName { get; set; }
	public Blob fileBody { get; set; }
	public List<Attachment> fileList { get; set; }

	public string loadCsvFlg { get; set; }
	private string [] itmsVal { get; set; }
	/* CSVファイル出力 */
	public Pagereference loadCsv() {
		Attachment att = new Attachment();
		att.Body = fileBody;
		att.Name = fileName;

		//att.ParentId = searchResultList.get(0).Id;
		//insert att;

		string fileContent = fileBody.toString();
		itmsVal = fileContent.split('n');
		List<A01_DaylySales__c> insList = new List<A01_DaylySales__c>();
		integer count = 0;
		for (string rowVal :itmsVal) {
			count ++;
			system.debug('XXXXX' + rowVal);
			string[] vals = rowVal.split(',');
			for (string val :vals) {
				/*
				 A01_DaylySales__c rec = new A01_DaylySales__c();

				 rec.name = 'TestData' + count;
				 rec.StoreNoDay__c = '1001_20191027';
				 rec.StoreR__c = '1';
				 rec.Day__c = '2';
				 rec.Sales__c = 3;
				 rec.Cost__c = 4;
				 rec.Profit__c = 5;
				 rec.CostHydroelectric__c = 6;
				 rec.CostSalary__c = 7;
				 rec.CostRental__c = 8;

				 insList.add(rec);
				 */
			}
		}
		/*
		 insert insList;
		 */

		getLoadFiles();
		att = null;
		return null;
	}
	private void getLoadFiles() {
		fileList = [select Id, Name, ParentId from Attachment];
	}
}