force-app/main/default/objects/A01_DaylySales__c/A01_DaylySales__c.object-meta.xml
<CustomObject>
    <label>A01_日次売上</label>
    <nameField>
        <label>A01_日次売上名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_DaylySales__c/fields/CalculationStatus__c.field-meta.xml
<CustomField>
    <fullName>CalculationStatus__c</fullName>
    <label>集計フラグ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>未集計</fullName>
                <default>true</default>
                <label>未集計</label>
            </value>
            <value>
                <fullName>集計済</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/CostSalary__c.field-meta.xml
<CustomField>
    <fullName>CostSalary__c</fullName>
    <label>費用(給料)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>年月日</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <label>売上</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/A01_DaylySales_TotalingHandlerTest.cls
@isTest
public class A01_DaylySales_TotalingHandlerTest {

    /** 正常パターン①*/
    @isTest static void testCheckItemValue_Normal_01() {
        System.Test.startTest();
        //データ作成
        createDataNormal();
        System.Test.stopTest();
        //テスト結果確認
        list<A01_DaylySales__c> retList = [select Id,name,CalculationStatus__c,Sales__c,Day__c,CostSalary__c  from A01_DaylySales__c];
        
        system.assertEquals('テスト名前', retList.get(0).name);
        system.assertEquals('集計済', retList.get(0).CalculationStatus__c);
        
    }

    /** 異常パターン①*/
    @isTest static void testCheckItemValue_Error_01() {
        System.Test.startTest();
        //データ作成
        try {
            createDataError();
        } catch(Exception e) {
            system.debug('XXXXX'+e.getMessage());
        }
        
    }
    //テストデータ準備
    private static void createDataNormal() {
        A01_DaylySales__c obj = new A01_DaylySales__c();
        obj.name = 'テスト名前';
        obj.Day__c = system.today();
        obj.CalculationStatus__c = '未集計';
        obj.Sales__c = 1000;
        insert obj;
    }
    //テストデータ準備
    private static void createDataError() {
        A01_DaylySales__c obj = new A01_DaylySales__c();
        obj.name = 'テスト名前';
        obj.Day__c = system.today();
        obj.CalculationStatus__c = '未集計';
        obj.Sales__c = 1000;
        insert obj;
    }


}