force-app/main/default/objects/A01_DaylySales__c/A01_DaylySales__c.object-meta.xml
<CustomObject>
    <label>A01_日次売上</label>
    <nameField>
        <label>A01_日次売上名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_DaylySales__c/fields/CostHydroelectric__c.field-meta.xml
<CustomField>
    <fullName>CostHydroelectric__c</fullName>
    <label>費用(水電)</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/CostRental__c.field-meta.xml
<CustomField>
    <fullName>CostRental__c</fullName>
    <label>費用(賃貸)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/CostSalary__c.field-meta.xml
<CustomField>
    <fullName>CostSalary__c</fullName>
    <label>費用(給料)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>年月日</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <label>利益</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <label>売上</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/StoreR__c.field-meta.xml
<CustomField>
    <fullName>StoreR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>販売店情報</label>
    <referenceTo>A01_Store__c</referenceTo>
    <relationshipLabel>A01_日次売上</relationshipLabel>
    <relationshipName>A01</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/A01_MonthlySales__c.object-meta.xml
<CustomObject>
    <label>A01_月次売上</label>
    <nameField>
        <label>A01_月次売上名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_MonthlySales__c/fields/Monthly__c.field-meta.xml
<CustomField>
    <fullName>Monthly__c</fullName>
    <label>年月</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/MonthlySales__c.field-meta.xml
<CustomField>
    <fullName>MonthlySales__c</fullName>
    <label>月次売上</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/StoreNoMonthly__c.field-meta.xml
<CustomField>
    <fullName>StoreNoMonthly__c</fullName>
    <formula>StoreR__r.StoreNo__c  &amp; &#39;_&#39; &amp;   TEXT(YEAR(Monthly__c ))  &amp; &#39;年&#39; &amp; TEXT( MONTH(Monthly__c ))  &amp; &#39;月&#39;</formula>
    <label>店番年月</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/StoreR__c.field-meta.xml
<CustomField>
    <fullName>StoreR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>販売店情報</label>
    <referenceTo>A01_Store__c</referenceTo>
    <relationshipLabel>A01_月次売上</relationshipLabel>
    <relationshipName>A011</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/A01_Store__c/A01_Store__c.object-meta.xml
<CustomObject>
    <label>A01_販売店情報</label>
    <nameField>
        <label>A01_販売店情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_Store__c/fields/StoreNo__c.field-meta.xml
<CustomField>
    <fullName>StoreNo__c</fullName>
    <label>店番</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/A01_DaylySales_Totalization_Bat.cls
public class A01_DaylySales_Totalization_Bat {
    public A01_DaylySales_Totalization_Bat() {}
    
    public string main(boolean flg,string storeName) {
        if (!flg) {
            return '1日ではないので、実施できません。';
        }
        //①販売店の日次売上を抽出する
        list<A01_DaylySales__c> retList = getDaylySalesListInfo(storeName);

        //②日次の情報を集計して、月次売上に登録する
        if (retList != null) {
            calculateMonthlySales(retList);
            return '登録が成功しました。';
        } else {
            return '検索結果はありません。';
        }
    }

    private list<A01_DaylySales__c> getDaylySalesListInfo(string storeName){
        list<A01_DaylySales__c> lst = 
            [select Id,Name,Day__c,StoreR__r.Id,StoreR__r.StoreNo__c,Sales__c,CostSalary__c,CostHydroelectric__c,CostRental__c,Profit__c from A01_DaylySales__c
            where StoreR__r.Name = :storeName];
        if (lst.size() > 0) {
            return lst;
        } else {
            return null;
        }
    }

    private void calculateMonthlySales(list<A01_DaylySales__c> daylyList){
        Decimal sales = 0;
        for (A01_DaylySales__c daylyRec : daylyList) {
            sales += daylyRec.Sales__c;  //A01_日次売上・売上
        }
        //月次売上の登録
        A01_MonthlySales__c insertData = new A01_MonthlySales__c();
        insertData.MonthlySales__c = sales;  //月次売上
        insertData.Monthly__c = string.valueof(system.Date.today()).replaceAll('-', '').left(6); //年月
        insertData.StoreR__c = daylyList.get(0).StoreR__r.Id;        //販売店情報
        insertData.StoreNoMonthly__c = daylyList.get(0).StoreR__r.StoreNo__c+'202003';//店番_年月
        insert insertData;
        
    }
}