force-app/main/default/objects/A01_DaylySales__c/A01_DaylySales__c.object-meta.xml
<CustomObject>
    <label>A01_日次売上</label>
    <nameField>
        <label>A01_日次売上名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_DaylySales__c/fields/CostHydroelectric__c.field-meta.xml
<CustomField>
    <fullName>CostHydroelectric__c</fullName>
    <label>費用(水電)</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/CostRental__c.field-meta.xml
<CustomField>
    <fullName>CostRental__c</fullName>
    <label>費用(賃貸)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/CostSalary__c.field-meta.xml
<CustomField>
    <fullName>CostSalary__c</fullName>
    <label>費用(給料)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>年月日</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <label>利益</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <label>売上</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_DaylySales__c/fields/StoreR__c.field-meta.xml
<CustomField>
    <fullName>StoreR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>販売店情報</label>
    <referenceTo>A01_Store__c</referenceTo>
    <relationshipLabel>A01_日次売上</relationshipLabel>
    <relationshipName>A01</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/A01_MonthlySales__c.object-meta.xml
<CustomObject>
    <label>A01_月次売上</label>
    <nameField>
        <label>A01_月次売上名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_MonthlySales__c/fields/MonthlySales__c.field-meta.xml
<CustomField>
    <fullName>MonthlySales__c</fullName>
    <label>月次売上</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/StoreR__c.field-meta.xml
<CustomField>
    <fullName>StoreR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>販売店情報</label>
    <referenceTo>A01_Store__c</referenceTo>
    <relationshipLabel>A01_月次売上</relationshipLabel>
    <relationshipName>A011</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/A01_Store__c/A01_Store__c.object-meta.xml
<CustomObject>
    <label>A01_販売店情報</label>
    <nameField>
        <label>A01_販売店情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_Store__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>アドレス</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_Store__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>郵便番号</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_Store__c/fields/StoreName__c.field-meta.xml
<CustomField>
    <fullName>StoreName__c</fullName>
    <label>店名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_Store__c/fields/StoreNo__c.field-meta.xml
<CustomField>
    <fullName>StoreNo__c</fullName>
    <label>店番</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/A01_DaylySales_Totalization_BatTest.cls
@isTest
public class A01_DaylySales_Totalization_BatTest {
    static testMethod void testGetDaylySalesListInfo001(){
        insertData('大崎支店');

        A01_DaylySales_Totalization_Bat bat = new A01_DaylySales_Totalization_Bat(); 
        string retMessage = bat.main(true,'大崎支店');


        //登録結果の抽出
        list<A01_MonthlySales__c> exceptedList = [select Id,Name,StoreR__r.Name,MonthlySales__c from A01_MonthlySales__c];
        A01_MonthlySales__c exceptedData = exceptedList.get(0);


        //登録結果と予想値の確認
        system.assertEquals('登録が成功しました。', retMessage);
        system.assertEquals(300, exceptedData.MonthlySales__c);
        system.assertEquals('大崎支店', exceptedData.StoreR__r.Name);
    }

    static testMethod void testGetDaylySalesListInfo002(){
        insertData('大崎支店');

        A01_DaylySales_Totalization_Bat bat = new A01_DaylySales_Totalization_Bat(); 
        string retMessage = bat.main(false,'大崎支店');

        list<A01_MonthlySales__c> exceptedList = [select Id,Name,StoreR__r.Name,MonthlySales__c from A01_MonthlySales__c];

        system.assertEquals('1日ではないので、実施できません。', retMessage);
        system.assertEquals(0, exceptedList.size());
    }

    static testMethod void testGetDaylySalesListInfo003(){
        insertData('大阪支店');

        A01_DaylySales_Totalization_Bat bat = new A01_DaylySales_Totalization_Bat(); 
        string retMessage = bat.main(true,'大崎支店');

        list<A01_MonthlySales__c> exceptedList = [select Id,Name,StoreR__r.Name,MonthlySales__c from A01_MonthlySales__c];

        system.assertEquals('検索結果はありません。', retMessage);
        system.assertEquals(0, exceptedList.size());
    }

    private static void insertData(string name) {
        A01_Store__c store = new A01_Store__c();
        store.name = name;
        store.StoreNo__c = '1001';
        
        store.StoreName__c = name;
        store.Address__c = '大崎駅';
        store.PostalCode__c = '212-0055';
        insert store;

        list<A01_DaylySales__c> insList = new list<A01_DaylySales__c>(); 
        A01_DaylySales__c dayInfo = new A01_DaylySales__c();
        integer index = 0;
        while (index < 3) {
            index ++;
            dayInfo = new A01_DaylySales__c();
            dayInfo.Name = name;
            dayInfo.StoreR__c = store.Id;
            dayInfo.Day__c = system.today().addDays(index);
            dayInfo.Sales__c = 100;
            dayInfo.CostSalary__c = 100;
            dayInfo.CostHydroelectric__c = 100;
            dayInfo.CostRental__c = 100;
            dayInfo.Profit__c = 100;
            insList.add(dayInfo);
        }
        insert insList;

    }
}