force-app/main/default/objects/A01_MonthlySales__c/A01_MonthlySales__c.object-meta.xml
<CustomObject>
    <label>A01_月次売上</label>
    <nameField>
        <label>A01_月次売上名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_MonthlySales__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>承認ステータス</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>未申請</fullName>
                <default>true</default>
                <label>未申請</label>
            </value>
            <value>
                <fullName>申請中</fullName>
            </value>
            <value>
                <fullName>承認済</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/Monthly__c.field-meta.xml
<CustomField>
    <fullName>Monthly__c</fullName>
    <label>年月</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/MonthlyCost__c.field-meta.xml
<CustomField>
    <fullName>MonthlyCost__c</fullName>
    <label>月次原価</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/MonthlyExpense__c.field-meta.xml
<CustomField>
    <fullName>MonthlyExpense__c</fullName>
    <label>月次費用</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/MonthlySales__c.field-meta.xml
<CustomField>
    <fullName>MonthlySales__c</fullName>
    <label>月次売上</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/StoreR__c.field-meta.xml
<CustomField>
    <fullName>StoreR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>販売店情報</label>
    <referenceTo>A01_Store__c</referenceTo>
    <relationshipLabel>A01_月次売上</relationshipLabel>
    <relationshipName>A011</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/A01_Store__c/A01_Store__c.object-meta.xml
<CustomObject>
    <label>A01_販売店情報</label>
    <nameField>
        <label>A01_販売店情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_Store__c/fields/StoreName__c.field-meta.xml
<CustomField>
    <fullName>StoreName__c</fullName>
    <label>店名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/A01_StoreMonthlySalesPdfControl.cls
public class A01_StoreMonthlySalesPdfControl {
	public list<A01_MonthlySales__c> pdfList { get; set; }
	ApexPages.StandardSetController controller { get; set; }
	//引数・店名
	public string paramStoreName { get; set; }
	//引数・年月
	public string paramMonth { get; set; }
	//引数・承認ステータス
	public string paramStatus { get; set; }
	//ファイル名
	public string filename { get; set; }

	public Pagereference execute() {
		system.debug('XXXXfunck');
		string param1 = ApexPages.currentPage().getParameters().get('paramStoreName');
		//年月
		string param2 = ApexPages.currentPage().getParameters().get('paramMonth');
		//承認ステータス
		string param3 = ApexPages.currentPage().getParameters().get('paramStatus');

		string sql = getSearchSql(param1, param2, param3);

		//ページング条件設定
		pdfList =(list<A01_MonthlySales__c>) Database.query(sql);
		
		filename = 'PDF_Sample';
		//ヘッダ情報設定
		return null;
	}

	/* 検索SQLファイル作成 */
	private string getSearchSql(string inputStoreNm, string inputMonth, string pickedStatus) {

		string sql = 'select Id, StoreR__r.StoreName__c ,Monthly__c, MonthlySales__c, MonthlyExpense__c, MonthlyCost__c, ApprovalStatus__c from A01_MonthlySales__c where Id != null ';

		if(inputMonth != null && string.isNotEmpty(inputMonth)) {
			sql += ' and Monthly__c = ' + '\'' + inputMonth + '\'';
		}
		
		if(pickedStatus != null && string.isNotEmpty(pickedStatus)) {
			sql += ' and ApprovalStatus__c = ' + '\'' + pickedStatus + '\'';
		}
		sql += ' order by Monthly__c';
		return sql;
	}
}