force-app/main/default/objects/A01_MonthlySales__c/A01_MonthlySales__c.object-meta.xml
<CustomObject>
    <label>A01_月次売上</label>
    <nameField>
        <label>A01_月次売上名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_MonthlySales__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>承認ステータス</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>未申請</fullName>
                <default>true</default>
                <label>未申請</label>
            </value>
            <value>
                <fullName>申請中</fullName>
            </value>
            <value>
                <fullName>承認済</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/Authorizer__c.field-meta.xml
<CustomField>
    <fullName>Authorizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>承認者</label>
    <referenceTo>User</referenceTo>
    <relationshipName>A011</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/Monthly__c.field-meta.xml
<CustomField>
    <fullName>Monthly__c</fullName>
    <label>年月</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/MonthlyCost__c.field-meta.xml
<CustomField>
    <fullName>MonthlyCost__c</fullName>
    <label>月次原価</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/MonthlyExpense__c.field-meta.xml
<CustomField>
    <fullName>MonthlyExpense__c</fullName>
    <label>月次費用</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/MonthlySales__c.field-meta.xml
<CustomField>
    <fullName>MonthlySales__c</fullName>
    <label>月次売上</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/StoreNoMonthly__c.field-meta.xml
<CustomField>
    <fullName>StoreNoMonthly__c</fullName>
    <formula>StoreR__r.StoreNo__c  &amp; &#39;_&#39; &amp;   TEXT(YEAR(Monthly__c ))  &amp; &#39;年&#39; &amp; TEXT( MONTH(Monthly__c ))  &amp; &#39;月&#39;</formula>
    <label>店番年月</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/StoreR__c.field-meta.xml
<CustomField>
    <fullName>StoreR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>販売店情報</label>
    <referenceTo>A01_Store__c</referenceTo>
    <relationshipLabel>A01_月次売上</relationshipLabel>
    <relationshipName>A011</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/A01_Store__c/A01_Store__c.object-meta.xml
<CustomObject>
    <label>A01_販売店情報</label>
    <nameField>
        <label>A01_販売店情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_Store__c/fields/StoreName__c.field-meta.xml
<CustomField>
    <fullName>StoreName__c</fullName>
    <label>店名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_Store__c/fields/StoreNo__c.field-meta.xml
<CustomField>
    <fullName>StoreNo__c</fullName>
    <label>店番</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/A01_StoreMonthlySalesControl.cls
public with sharing class A01_StoreMonthlySalesControl {
	public A01_StoreMonthlySalesControl() {

	}
	//販売店名
	public string inputStoreName { get; set; }
	//年月日
	public string inputMonth { get; set; }

	/** 選択値 */
	public String pickedStatus { get; set; }
	/** 選択オプション取得 */
	public List<SelectOption> getStatusList() {

		List<SelectOption> options = new List<SelectOption>();
		options.add(new SelectOption('', ''));
		options.add(new SelectOption('未申請', '未申請'));
		options.add(new SelectOption('申請中', '申請中'));
		options.add(new SelectOption('承認済', '承認済'));
		return options;
	}
	//画面明細リストオブジェクト
	public list<A01_MonthlySales__c> searchResultList { get; set; }

	/**
	 * search 検索ボタンをクリックする
	 *
	 * @@ Return PageReference: Return 販売店売上一覧画面へ遷移
	 */
	public PageReference search() {

		ssc = new ApexPages.StandardSetController(Database.getQueryLocator(getSearchSql()));
		ssc.setPageSize(5);

		searchResultList = searchObjects(1);

		return null;
	}

	public Integer totalpage { get; set; }
	public ApexPages.StandardSetController ssc { get; set; }
	// 最初のページへ
	public void first() {
		ssc.first();
		searchResultList = searchObjects(ssc.getPageNumber());
	}
	// 前のページへ
	public void previous() {
		ssc.previous();
		searchResultList = searchObjects(ssc.getPageNumber());
	}
	// 次のページへ
	public void next() {
		ssc.next();
		searchResultList = searchObjects(ssc.getPageNumber());
	}
	// 最後のページへ
	public void last() {
		ssc.last();
		searchResultList = searchObjects(totalpage);
	}

	/* 検索を実施する */
	private list<A01_MonthlySales__c> searchObjects(integer pageCount) {

		integer startOffset =(pageCount - 1) * ssc.getPageSize();
		string sql = getSearchSql();
		//ページング条件設定
		sql += ' limit ' + ssc.getPageSize() + ' offset ' + startOffset;

		system.debug('SQLXXXXX' + sql);
		list<A01_MonthlySales__c> retList =(list<A01_MonthlySales__c>) Database.query(sql);

		totalpage = getPageCount(ssc.getResultSize(), ssc.getPageSize());


		return retList;
	}

	/* 検索SQLファイル作成 */
	private string getSearchSql() {
		string sql = 'select Id, StoreNoMonthly__c, StoreR__c, Monthly__c, MonthlySales__c, '
		+ 'MonthlyExpense__c, MonthlyCost__c, ApprovalStatus__c, Authorizer__c,'
		+ 'StoreR__r.StoreNo__c,StoreR__r.StoreName__c from A01_MonthlySales__c where Id != null ';

		if(string.isNotEmpty(inputMonth)) {
			sql += ' and Monthly__c = ' + '\'' + inputMonth + '\'';
		}
		if(string.isNotEmpty(pickedStatus)) {
			sql += ' and ApprovalStatus__c = ' + '\'' + pickedStatus + '\'';
		}
		sql += ' order by Monthly__c';
		return sql;
	}
	/**
	 * getPageCount ページ総件数の算出
	 *
	 * ## recordCounts (integer): recordCounts レコード件数}
	 * ## pageSize (integer): pageSize ページ毎のレコード件数}
	 * @@ Return integer: Return ページ件数
	 */
	private integer getPageCount(integer recordCounts, integer pageSize) {
		//総頁数
		integer pageCount = recordCounts / pageSize;
		//余りを算出する
		integer pageMod = math.mod(recordCounts, pageSize);

		if(pageMod > 0) {
			//余りがある場合、頁数に1を加算する
			pageCount ++;
		}
		return pageCount;
	}
	/* PDFファイル出力 */
	public Pagereference printPdf() {

		PageReference pdfPage = new PageReference('/apex/A01_StoreMonthlySalesPdf' + getUrlParam());
		pdfPage.setRedirect(false);

		return pdfPage;
	}
	/* CSVファイル出力 */
	public Pagereference printCsv() {

		PageReference csvPage = new PageReference('/apex/A01_StoreMonthlySalesCsv' + getUrlParam());
		csvPage.setRedirect(false);

		return csvPage;
	}

	private string getUrlParam() {
		string urlStoreName = '';
		string urlMonth = '';
		string urlStatus = '';
		if(string.isNotEmpty(inputStoreName)) {
			urlStoreName = inputStoreName;
		}
		if(string.isNotEmpty(inputMonth)) {
			urlMonth = inputMonth;
		}
		if(string.isNotEmpty(pickedStatus)) {
			urlStatus = pickedStatus;
		}

		return '?paramStoreName=' + urlStoreName + '&paramMonth=' + urlMonth + '&paramStatus=' + urlStatus;
	}
}