force-app/main/default/objects/A01_MonthlySales__c/A01_MonthlySales__c.object-meta.xml
<CustomObject>
    <label>A01_月次売上</label>
    <nameField>
        <label>A01_月次売上名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_MonthlySales__c/fields/Monthly__c.field-meta.xml
<CustomField>
    <fullName>Monthly__c</fullName>
    <label>年月</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/MonthlySales__c.field-meta.xml
<CustomField>
    <fullName>MonthlySales__c</fullName>
    <label>月次売上</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/A01_MonthlySales__c/fields/StoreR__c.field-meta.xml
<CustomField>
    <fullName>StoreR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>販売店情報</label>
    <referenceTo>A01_Store__c</referenceTo>
    <relationshipLabel>A01_月次売上</relationshipLabel>
    <relationshipName>A011</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/A01_Store__c/A01_Store__c.object-meta.xml
<CustomObject>
    <label>A01_販売店情報</label>
    <nameField>
        <label>A01_販売店情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_Store__c/fields/OpenStatus__c.field-meta.xml
<CustomField>
    <fullName>OpenStatus__c</fullName>
    <label>開店状況</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>営業中</fullName>
            </value>
            <value>
                <fullName>閉店</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/A01_Store__c/fields/StoreLevel__c.field-meta.xml
<CustomField>
    <fullName>StoreLevel__c</fullName>
    <label>ラベル</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>一般店舗</fullName>
            </value>
            <value>
                <fullName>中級店舗</fullName>
            </value>
            <value>
                <fullName>上級店舗</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/A01_Store__c/fields/StoreNo__c.field-meta.xml
<CustomField>
    <fullName>StoreNo__c</fullName>
    <label>店番</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/A01_StoreLevelUp_Schedulable.cls
global class A01_StoreLevelUp_Schedulable implements Schedulable {
    global void execute(SchedulableContext ctx) {
        date sysDate = system.today();

        system.debug('システム日付：'+sysDate);
        if (sysDate.day() == 1) {
            //1日の場合、先月の売り上げにより、全部店舗のラベルを調整する
            doSomething();
        }
    }
    private void doSomething() {
        //営業中の店舗を検索する
        list<A01_Store__c> storeList = [select Id,StoreLevel__c,StoreNo__c from A01_Store__c where OpenStatus__c = '営業中'];

        list<string> storeIds = new list<string>();
        for(A01_Store__c rec : storeList) {
            storeIds.add(rec.Id);
        }
        
        
        date sysDate = system.today();
        //1か月前の1日
        date monthlyDate = sysDate.addMonths(-1);
        //月次売上の情報を検索する
        list<A01_MonthlySales__c> monthlySalesList = [select Id,StoreR__r.StoreNo__c,MonthlySales__c from A01_MonthlySales__c where StoreR__r.Id in :storeIds and Monthly__c = :monthlyDate];
        

        Map<String,Decimal> storeSalesMap = new Map<String,Decimal>();
        for (A01_MonthlySales__c rec : monthlySalesList) {
            //各店舗の月次売上をMapに保存する
            storeSalesMap.put(rec.StoreR__r.StoreNo__c, rec.MonthlySales__c);
        }

        Set<string> keyVals = storeSalesMap.keySet();
        Decimal salesVal = 0;
        for(A01_Store__c rec : storeList) {
            if (keyVals.contains(rec.StoreNo__c)) {
                salesVal = storeSalesMap.get(rec.StoreNo__c);
                if (salesVal <= 100000) {
                    rec.StoreLevel__c = '一般店舗';
                } else if (salesVal > 100000 && salesVal <= 500000) {
                    rec.StoreLevel__c = '中級店舗';
                } else {
                    rec.StoreLevel__c = '上級店舗';
                }
            }
        }
        update storeList;
    }
}