force-app/main/default/objects/A01_Store__c/A01_Store__c.object-meta.xml
<CustomObject>
    <label>A01_販売店情報</label>
    <nameField>
        <label>A01_販売店情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/A01_Store__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>アドレス</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_Store__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>郵便番号</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_Store__c/fields/StoreLevel__c.field-meta.xml
<CustomField>
    <fullName>StoreLevel__c</fullName>
    <label>ラベル</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>一般店舗</fullName>
            </value>
            <value>
                <fullName>中級店舗</fullName>
            </value>
            <value>
                <fullName>上級店舗</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/A01_Store__c/fields/StoreName__c.field-meta.xml
<CustomField>
    <fullName>StoreName__c</fullName>
    <label>店名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A01_Store__c/fields/StoreNo__c.field-meta.xml
<CustomField>
    <fullName>StoreNo__c</fullName>
    <label>店番</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/A01_Exception_Sample_Controller.cls
public class A01_Exception_Sample_Controller {

    /**異常：NullPointerException*/
    public static void tryNullPointerException() {
        string val = null;
        try {
            val.toLowerCase();
        } catch(NullPointerException e) {
            system.debug('XXXXXX:'+e.getDmlMessage(0));
            throw e;
        }
    }

    /**異常：DmlException*/
    public static void tryDmlException() {
        try {
            A01_Store__c store = new A01_Store__c();
            store.Name = '大崎支店';
            store.StoreNo__c = '1001';
            store.StoreName__c = '大崎支店';
            store.StoreLevel__c = '一般店舗';
            //store.Address__c = '大崎駅';
            //store.PostalCode__c = '2120001';
            insert store;
        } catch (DmlException e) {
            System.debug('XXXXX:'+e.getDmlMessage(0));
            throw e;
        }
    }

    /**異常：ListException*/
    public static void tryListException() {
        try {
            List<String> lst = new List<String>();
            lst.add('文字列１');

            system.debug(lst.get(2));
        } catch (ListException e) {
            System.debug('XXXXX:'+e.getDmlMessage(0));
            throw e;
        }
    }
 
    
}